# Generated by Django 6.0.8 on 2026-08-16 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
        ('services', '0003_servicelocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='providers.providerprofile')),
            ],
            options={
                'ordering': ['weekday', 'start_time'],
                'indexes': [models.Index(fields=['provider', 'weekday', 'is_active'], name='services_pr_provide_77652f_idx')],
                'constraints': [models.UniqueConstraint(fields=('provider', 'weekday'), name='unique_provider_weekday_availability')],
            },
        ),
    ]
