# Generated by Django 6.0.8 on 2026-08-16 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
        ('services', '0004_provideravailability'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='service',
            name='services_se_provide_679d85_idx',
        ),
        migrations.RemoveIndex(
            model_name='service',
            name='services_se_categor_b50c86_idx',
        ),
        migrations.AddField(
            model_name='service',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['provider', 'is_published'], name='services_se_provide_812c80_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['category', 'is_published'], name='services_se_categor_7809a3_idx'),
        ),
        migrations.RemoveField(
            model_name='service',
            name='is_active',
        ),
    ]
