# Generated by Django 6.0.8 on 2026-08-23 14:11

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_remove_service_services_se_provide_679d85_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='service image'),
        ),
    ]
