# Generated by Django 6.0.8 on 2026-08-19 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0003_alter_booking_total_amount'),
        ('providers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conversation', to='bookings.booking')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_conversations', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='providers.providerprofile')),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['customer', '-updated_at'], name='chat_conver_custome_9c3013_idx'), models.Index(fields=['provider', '-updated_at'], name='chat_conver_provide_4ab057_idx')],
            },
        ),
    ]
