# Generated by Django 6.0.8 on 2026-08-16 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('providers', '0001_initial'),
        ('services', '0005_remove_service_services_se_provide_679d85_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('customer_notes', models.TextField(blank=True)),
                ('provider_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='providers.providerprofile')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='services.service')),
            ],
            options={
                'ordering': ['-booking_date', '-start_time'],
                'indexes': [models.Index(fields=['provider', 'booking_date', 'status'], name='bookings_bo_provide_71c3df_idx'), models.Index(fields=['customer', 'booking_date', 'status'], name='bookings_bo_custome_d3a4bb_idx'), models.Index(fields=['service', 'booking_date'], name='bookings_bo_service_e95de1_idx')],
            },
        ),
    ]
